### ISSUE TITLE
Getting started -> 3. Native or Lazy

### ISSUE THREAD

**Issue by ipostanogov** [terl/lazysodium-docs#4]
Looks like the code from [3. Native or Lazy](https://github.com/terl/lazysodium-docs/blob/d6e235e915e3a94133bedbdf944f197129b1ec17/getting-started.md#3-native-or-lazy) is obsolete since https://github.com/terl/lazysodium-java/commit/b1254ecf6f72abfc5e4bf06f922d15e2392ec2d3.

**Comment by gurpreet-** [comment]
Hi @ipostanogov,

Thanks for reporting this, I have fixed it.

👍
